export default [
  {
    preview: 'https://i.ibb.co/NTV2hwT/img-00.jpg',
    original: 'https://i.ibb.co/NTV2hwT/img-00.jpg',
    description:
      'Зберіть кубик Рубіка, щоб дізнатися, де потрібно порахувати всі ліхтарі',
    ansId: 'ans-00',
    trueAns: '26',
  },
  {
    preview: 'https://i.ibb.co/n0NDPdW/img-1-400.jpg',
    original: 'https://i.ibb.co/7Q9zHgb/img-1.jpg',
    description: 'Цифри в моделі генератора поблизу?',
    ansId: 'ans-01',
    trueAns: '165',
  },
  {
    preview: 'https://i.ibb.co/pjbvCv0/img-2-400.jpg',
    original: 'https://i.ibb.co/S5bfh7v/img-2.jpg',
    description: 'Кількість сходинок біля?',
    ansId: 'ans-02',
    trueAns: '5',
  },
  {
    preview: 'https://i.ibb.co/vstPzTM/img-3-400.jpg',
    original: 'https://i.ibb.co/SV9c53Z/img-3.jpg',
    description:
      'З цього об`єкта дуже гарний краєвид. На якій кількості опор тримається його дах?',
    ansId: 'ans-03',
    trueAns: '13',
  },
  {
    preview: 'https://i.ibb.co/JRCTx7X/img-4-400.jpg',
    original: 'https://i.ibb.co/ZBKzvXX/img-4.jpg',
    description: 'Кількість віконець над цим кнехтом?',
    ansId: 'ans-04',
    trueAns: '3',
  },
  {
    preview: 'https://i.ibb.co/G959HYz/img-5-400.jpg',
    original: 'https://i.ibb.co/f4km8g1/img-5.jpg',
    description: 'Скільки блакитних куль під стелею у крамниці',
    ansId: 'ans-05',
    trueAns: '11',
  },
  {
    preview: 'https://i.ibb.co/ZVh5J3n/img-06-400.jpg',
    original: 'https://i.ibb.co/zNzMHWf/img-06.jpg',
    description: 'Номер автівки?',
    ansId: 'ans-06',
    trueAns: '9477',
  },
  {
    preview: 'https://i.ibb.co/wKb70Ft/img-07-400.jpg',
    original: 'https://i.ibb.co/2v6cNq9/img-07.jpg',
    description: 'Номер причепа?',
    ansId: 'ans-07',
    trueAns: '0268',
  },
  {
    preview: 'https://i.ibb.co/GWTTHCq/img-08-400.jpg',
    original: 'https://i.ibb.co/tz5jM4H/img-08.jpg',
    description: 'Температура повітря?',
    ansId: 'ans-08',
    trueAns: '29',
  },
  {
    preview: 'https://i.ibb.co/chgzTKm/img-09-400.jpg',
    original: 'https://i.ibb.co/BrvyP1V/img-09.jpg',
    description: 'Йдіть за рукою дівчини. Пароль Wi-Fi?',
    ansId: 'ans-09',
    trueAns: '88888888',
  },
  {
    preview: 'https://i.ibb.co/MgJbMh7/img-10-400.jpg',
    original: 'https://i.ibb.co/Gp1wMxz/img-10.jpg',
    description: 'На якій сходинці стоїть пляшка?',
    ansId: 'ans-10',
    trueAns: '7',
  },
  {
    preview: 'https://i.ibb.co/JHj8QnT/img-11-400.jpg',
    original: 'https://i.ibb.co/G5W5gLm/img-11.jpg',
    description: 'Неподалік від цього туриста є білі “чупа-чупси”',
    ansId: 'ans-11',
    trueAns: '9',
  },
  {
    preview: 'https://i.ibb.co/V32W8yv/img-12-400.jpg',
    original: 'https://i.ibb.co/GnPj4sq/img-12.jpg',
    description: 'Скільки поряд столиків на ніжці?',
    ansId: 'ans-12',
    trueAns: '3',
  },
  {
    preview: 'https://i.ibb.co/wKxgDhN/img-14-400.jpg',
    original: 'https://i.ibb.co/7YSxzHs/img-14.jpg',
    description: 'Скільки пар завжди танцюють на цій алеї?',
    ansId: 'ans-14',
    trueAns: '12',
  },
];
